language: ruby
rvm:
  - 2.2
branches:
  only:
  - master
env:
  global:
  - secure: BuT+l5oVMr5G2qxmaHgEkJ64YtyhVAzHrobdUC4ismGQOJuebIjxwtAFzu4ctv43EaqSvWWVARHnje+YiU8jtvtx5oxR16BIxDjZ3FggeWAb6GvJjR8Wo2vf5E/AU+rdsjP/BwM46MLy8hdwyA0c271IBxf9fOgoJpDzj+sS2wxSJ2sOq2Zp2kv6uK2BWfSRAAWiVv5Y2Fpc//wlTSd5MTX8+QLBZf2yCyeQWbqUJ8WOzjtVDIW6C2z7UJH59P713gEUc7srqCKRXZ/BMEkMw71Y77BkTBiH5wK/R3Sxfhg7YzmULgWTjS6NR3+2Mv//tBbHOaVDzhB4ojgrmgisxTdnkEC6vhIEiNxIAulpiw5Xl5eEQktGWiPyHyuK9auzat9lHXIXZs7bvIsv8dE0HP32wBgmX7s92zCR2vrH2xJ5dQSWu6HWJscuKYftg6O2AwWUfAGqgJ8KbWlHq37asWcZlY706oB32P7bYuxiZUX+mNplQbIShL6+hOcGey1xqDyqVHeEo0v5Coba7vfOMFyPqbzzhus/zsMxjU89xy0HPw1LCuNdYJPUus1Pk6Zx+boOvpSNuyZhL/YgEc4JE+d56JxvsbTmtmUUQxTKVg0ChFdI9o7nB7m/nhSdRY3lDPAkZhDjpcPYLRwxHRgXiLOCsMbFkmIXTzzmMFGdq6g=
  - secure: u4xDQnt1X2EtW+T4H8M35urm025+lULQ8N4AvtSMc8fuh2CvDDemkc3nwCc3a+sxNaFojuTzc8tV44zfQKdoMykJZrptM/qFB59C2HeSlVLWimwMrwzDunB1UNme/Lnpp7vjvvrYD1s+AlkCrym83F+2eLKjbETLUd2F8b3lwQrn2NywzZyGoyXWziNjyNEVk28iA+yLNvK7JrG3F8vj3Td2sWqtHs3Ke/cFy0rwkhTAO8jile2CE5eTZxzc4gMxlrijHRa/eMq4/89otHnUi4RUNfNxq3umUd+miDzRvUfx+XfNlCG7DQH/ujfaZJYllLEA2ZqLvlP01EAsL4hbf0OBAv2EZw+hQcXUQ953UaS1haVhkh5TQWLbWQGgNIYBkUaT33XS9mGlb73qBPAGn9BygqPojKjuPe3Jrv3dEw0+pkLdP21nq8HkL6lXQotLjvkpjM/J03bvOEqBH3hPY5Zk9R9XqPhqqklKTmpRvyD4N7YenGximPTCeUaqyAC0LysiEtGRxX1E6Pb4XwKnU6zzB4Yetxl7JW6aQcMoXypN2k1RfxYjoNtbkLN5EH2B0eHmHfdT0Uq1aw6JZmVUWEjeka9rUzoL/d8MKTepSud698n0R74qHxx6Nw/OqF/nMa/IgO3/dhqJg27nKnqnqB8ATHNdMHCs2JkynJiJYps=
install: bundle install
script: bundle exec jekyll build
deploy:
  provider: s3
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: "liviu.io"
  local-dir: _site
