# Site settings
title: Liviu Damian
description: 'A DevOps Blog'
url: 'https://liviu.io'
baseurl: '/'
google_analytics: 'UA-41612528-2'
disqus_shortname: 'liviudm'

author:
  name: 'Liviu Damian'
  github_username:  liviudm
  linkedin_username:  liviudm

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'vendor']
